const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env.local' });

const supabase = createClient(
  process.env.REACT_APP_SUPABASE_URL,
  process.env.SUPABASE_SERVICE_ROLE_KEY
);

// O-words pronunciations (comprehensive list)
const pronunciations = {
  'oaf': 'OHF',
  'oak': 'OHK',
  'oaken': 'OHK-un',
  'oaks': 'OHKS',
  'oar': 'OR',
  'oars': 'ORZ',
  'oases': 'oh-AY-seez',
  'oasis': 'oh-AY-sis',
  'oat': 'OHT',
  'oath': 'OHTH',
  'oaths': 'OHTHS',
  'oatmeal': 'OHT-meel',
  'oats': 'OHTS',
  'obedience': 'oh-BEE-dee-unts',
  'obedient': 'oh-BEE-dee-unt',
  'obeisance': 'oh-BAY-sunts',
  'obelisk': 'OB-uh-lisk',
  'obese': 'oh-BEES',
  'obesity': 'oh-BEE-suh-tee',
  'obey': 'oh-BAY',
  'obeyed': 'oh-BAYD',
  'obeying': 'oh-BAY-ing',
  'obeys': 'oh-BAYZ',
  'obituary': 'oh-BICH-oo-er-ee',
  'object': 'OB-jikt',
  'objected': 'ob-JEK-tid',
  'objecting': 'ob-JEK-ting',
  'objection': 'ob-JEK-shun',
  'objections': 'ob-JEK-shunz',
  'objective': 'ob-JEK-tiv',
  'objectively': 'ob-JEK-tiv-lee',
  'objectives': 'ob-JEK-tivz',
  'objects': 'OB-jikts',
  'obligation': 'ob-luh-GAY-shun',
  'obligations': 'ob-luh-GAY-shunz',
  'obligatory': 'uh-BLIG-uh-tor-ee',
  'oblige': 'uh-BLYZ',
  'obliged': 'uh-BLYZD',
  'obliges': 'uh-BLY-jiz',
  'obliging': 'uh-BLY-jing',
  'oblique': 'uh-BLEEK',
  'obliterate': 'uh-BLIT-uh-rayt',
  'obliterated': 'uh-BLIT-uh-ray-tid',
  'obliterates': 'uh-BLIT-uh-rayts',
  'obliterating': 'uh-BLIT-uh-ray-ting',
  'obliteration': 'uh-blit-uh-RAY-shun',
  'oblivion': 'uh-BLIV-ee-un',
  'oblivious': 'uh-BLIV-ee-us',
  'oblong': 'OB-lawng',
  'obnoxious': 'ob-NOK-shus',
  'obscene': 'ob-SEEN',
  'obscenity': 'ob-SEN-uh-tee',
  'obscure': 'ob-SKYOOR',
  'obscured': 'ob-SKYOORD',
  'obscures': 'ob-SKYOORZ',
  'obscuring': 'ob-SKYOOR-ing',
  'obscurity': 'ob-SKYOOR-uh-tee',
  'observation': 'ob-zer-VAY-shun',
  'observations': 'ob-zer-VAY-shunz',
  'observatory': 'ob-ZER-vuh-tor-ee',
  'observe': 'ob-ZERV',
  'observed': 'ob-ZERVD',
  'observer': 'ob-ZER-ver',
  'observers': 'ob-ZER-verz',
  'observes': 'ob-ZERVZ',
  'observing': 'ob-ZER-ving',
  'obsess': 'ob-SES',
  'obsessed': 'ob-SEST',
  'obsesses': 'ob-SES-iz',
  'obsessing': 'ob-SES-ing',
  'obsession': 'ob-SESH-un',
  'obsessions': 'ob-SESH-unz',
  'obsessive': 'ob-SES-iv',
  'obstacle': 'OB-stuh-kul',
  'obstacles': 'OB-stuh-kulz',
  'obstinate': 'OB-stuh-nit',
  'obstruct': 'ob-STRUKT',
  'obstructed': 'ob-STRUK-tid',
  'obstructing': 'ob-STRUK-ting',
  'obstruction': 'ob-STRUK-shun',
  'obstructions': 'ob-STRUK-shunz',
  'obstructs': 'ob-STRUKTS',
  'obtain': 'ob-TAYN',
  'obtained': 'ob-TAYND',
  'obtaining': 'ob-TAY-ning',
  'obtains': 'ob-TAYNZ',
  'obtuse': 'ob-TOOS',
  'obvious': 'OB-vee-us',
  'obviously': 'OB-vee-us-lee',
  'occasion': 'uh-KAY-zhun',
  'occasional': 'uh-KAY-zhuh-nul',
  'occasionally': 'uh-KAY-zhuh-nuh-lee',
  'occasions': 'uh-KAY-zhunz',
  'occult': 'uh-KULT',
  'occupant': 'OK-yuh-punt',
  'occupants': 'OK-yuh-punts',
  'occupation': 'ok-yuh-PAY-shun',
  'occupational': 'ok-yuh-PAY-shuh-nul',
  'occupations': 'ok-yuh-PAY-shunz',
  'occupied': 'OK-yuh-pyd',
  'occupies': 'OK-yuh-pyze',
  'occupy': 'OK-yuh-py',
  'occupying': 'OK-yuh-py-ing',
  'occur': 'uh-KER',
  'occurred': 'uh-KERD',
  'occurrence': 'uh-KER-unts',
  'occurrences': 'uh-KER-un-siz',
  'occurring': 'uh-KER-ing',
  'occurs': 'uh-KERZ',
  'ocean': 'OH-shun',
  'oceanic': 'oh-shee-AN-ik',
  'oceans': 'OH-shunz',
  'ocelot': 'OH-suh-lot',
  'ochre': 'OH-ker',
  'octagon': 'OK-tuh-gon',
  'octagonal': 'ok-TAG-uh-nul',
  'octane': 'OK-tayn',
  'octave': 'OK-tiv',
  'october': 'ok-TOH-ber',
  'octopus': 'OK-tuh-pus',
  'odd': 'OD',
  'oddly': 'OD-lee',
  'oddness': 'OD-nis',
  'odds': 'ODZ',
  'ode': 'OHD',
  'odious': 'OH-dee-us',
  'odor': 'OH-der',
  'odorless': 'OH-der-lis',
  'odors': 'OH-derz',
  'odyssey': 'OD-uh-see',
  'off': 'AWF',
  'offbeat': 'AWF-beet',
  'offend': 'uh-FEND',
  'offended': 'uh-FEN-did',
  'offender': 'uh-FEN-der',
  'offenders': 'uh-FEN-derz',
  'offending': 'uh-FEN-ding',
  'offends': 'uh-FENDZ',
  'offense': 'uh-FENS',
  'offenses': 'uh-FEN-siz',
  'offensive': 'uh-FEN-siv',
  'offer': 'AW-fer',
  'offered': 'AW-ferd',
  'offering': 'AW-fer-ing',
  'offerings': 'AW-fer-ingz',
  'offers': 'AW-ferz',
  'offhand': 'AWF-hand',
  'offhandedly': 'AWF-han-did-lee',
  'office': 'AW-fis',
  'officer': 'AW-fuh-ser',
  'officers': 'AW-fuh-serz',
  'offices': 'AW-fuh-siz',
  'official': 'uh-FISH-ul',
  'officially': 'uh-FISH-uh-lee',
  'officials': 'uh-FISH-ulz',
  'offset': 'AWF-set',
  'offspring': 'AWF-spring',
  'often': 'AW-fun',
  'oh': 'OH',
  'oil': 'OYL',
  'oiled': 'OYLD',
  'oily': 'OY-lee',
  'oils': 'OYLZ',
  'ointment': 'OYNT-munt',
  'okay': 'oh-KAY',
  'old': 'OHLD',
  'older': 'OHL-der',
  'oldest': 'OHL-dist',
  'olive': 'OL-iv',
  'olives': 'OL-ivz',
  'olympic': 'uh-LIM-pik',
  'olympics': 'uh-LIM-piks',
  'omelet': 'OM-lit',
  'omen': 'OH-mun',
  'omens': 'OH-munz',
  'ominous': 'OM-uh-nus',
  'omission': 'oh-MISH-un',
  'omissions': 'oh-MISH-unz',
  'omit': 'oh-MIT',
  'omits': 'oh-MITS',
  'omitted': 'oh-MIT-id',
  'omitting': 'oh-MIT-ing',
  'on': 'ON',
  'once': 'WUNTS',
  'one': 'WUN',
  'oneness': 'WUN-nis',
  'ones': 'WUNZ',
  'oneself': 'wun-SELF',
  'ongoing': 'ON-goh-ing',
  'onion': 'UN-yun',
  'onions': 'UN-yunz',
  'online': 'on-LYN',
  'only': 'OHN-lee',
  'onset': 'ON-set',
  'onto': 'ON-too',
  'onus': 'OH-nus',
  'onward': 'ON-werd',
  'ooze': 'OOZ',
  'oozed': 'OOZD',
  'oozes': 'OO-ziz',
  'oozing': 'OO-zing',
  'opal': 'OH-pul',
  'opaque': 'oh-PAYK',
  'open': 'OH-pun',
  'opened': 'OH-pund',
  'opener': 'OH-puh-ner',
  'opening': 'OH-puh-ning',
  'openings': 'OH-puh-ningz',
  'openly': 'OH-pun-lee',
  'openness': 'OH-pun-nis',
  'opens': 'OH-punz',
  'opera': 'OP-er-uh',
  'operas': 'OP-er-uhz',
  'operate': 'OP-uh-rayt',
  'operated': 'OP-uh-ray-tid',
  'operates': 'OP-uh-rayts',
  'operating': 'OP-uh-ray-ting',
  'operation': 'op-uh-RAY-shun',
  'operational': 'op-uh-RAY-shuh-nul',
  'operations': 'op-uh-RAY-shunz',
  'operative': 'OP-er-uh-tiv',
  'operator': 'OP-uh-ray-ter',
  'operators': 'OP-uh-ray-terz',
  'opinion': 'uh-PIN-yun',
  'opinions': 'uh-PIN-yunz',
  'opium': 'OH-pee-um',
  'opponent': 'uh-POH-nunt',
  'opponents': 'uh-POH-nunts',
  'opportune': 'op-er-TOON',
  'opportunities': 'op-er-TOO-nuh-teez',
  'opportunity': 'op-er-TOO-nuh-tee',
  'oppose': 'uh-POHZ',
  'opposed': 'uh-POHZD',
  'opposes': 'uh-POH-ziz',
  'opposing': 'uh-POH-zing',
  'opposite': 'OP-uh-zit',
  'opposites': 'OP-uh-zits',
  'opposition': 'op-uh-ZISH-un',
  'oppress': 'uh-PRES',
  'oppressed': 'uh-PREST',
  'oppresses': 'uh-PRES-iz',
  'oppressing': 'uh-PRES-ing',
  'oppression': 'uh-PRESH-un',
  'oppressive': 'uh-PRES-iv',
  'opt': 'OPT',
  'opted': 'OP-tid',
  'optic': 'OP-tik',
  'optical': 'OP-ti-kul',
  'optics': 'OP-tiks',
  'optimal': 'OP-tuh-mul',
  'optimism': 'OP-tuh-mizm',
  'optimist': 'OP-tuh-mist',
  'optimistic': 'op-tuh-MIS-tik',
  'optimize': 'OP-tuh-myz',
  'optimized': 'OP-tuh-myzd',
  'optimizes': 'OP-tuh-my-ziz',
  'optimizing': 'OP-tuh-my-zing',
  'optimum': 'OP-tuh-mum',
  'option': 'OP-shun',
  'optional': 'OP-shuh-nul',
  'options': 'OP-shunz',
  'opts': 'OPTS',
  'opus': 'OH-pus',
  'or': 'OR',
  'oracle': 'OR-uh-kul',
  'oral': 'OR-ul',
  'orally': 'OR-uh-lee',
  'orange': 'OR-inj',
  'oranges': 'OR-in-jiz',
  'orbit': 'OR-bit',
  'orbital': 'OR-bi-tul',
  'orbited': 'OR-bi-tid',
  'orbiting': 'OR-bi-ting',
  'orbits': 'OR-bits',
  'orchard': 'OR-cherd',
  'orchards': 'OR-cherdz',
  'orchestra': 'OR-kis-truh',
  'orchestral': 'or-KES-trul',
  'orchestras': 'OR-kis-truhz',
  'orchestrate': 'OR-kis-trayt',
  'orchestrated': 'OR-kis-tray-tid',
  'orchestrates': 'OR-kis-trayts',
  'orchestrating': 'OR-kis-tray-ting',
  'orchid': 'OR-kid',
  'orchids': 'OR-kidz',
  'ordain': 'or-DAYN',
  'ordained': 'or-DAYND',
  'ordaining': 'or-DAY-ning',
  'ordains': 'or-DAYNZ',
  'ordeal': 'or-DEEL',
  'ordeals': 'or-DEELZ',
  'order': 'OR-der',
  'ordered': 'OR-derd',
  'ordering': 'OR-der-ing',
  'orderly': 'OR-der-lee',
  'orders': 'OR-derz',
  'ordinance': 'OR-duh-nuns',
  'ordinances': 'OR-duh-nun-siz',
  'ordinary': 'OR-duh-ner-ee',
  'ore': 'OR',
  'oregano': 'uh-REG-uh-noh',
  'oregon': 'OR-uh-gun',
  'ores': 'ORZ',
  'organ': 'OR-gun',
  'organic': 'or-GAN-ik',
  'organically': 'or-GAN-ik-lee',
  'organism': 'OR-guh-nizm',
  'organisms': 'OR-guh-nizmz',
  'organist': 'OR-guh-nist',
  'organization': 'or-guh-nuh-ZAY-shun',
  'organizational': 'or-guh-nuh-ZAY-shuh-nul',
  'organizations': 'or-guh-nuh-ZAY-shunz',
  'organize': 'OR-guh-nyz',
  'organized': 'OR-guh-nyzd',
  'organizer': 'OR-guh-ny-zer',
  'organizers': 'OR-guh-ny-zerz',
  'organizes': 'OR-guh-ny-ziz',
  'organizing': 'OR-guh-ny-zing',
  'organs': 'OR-gunz',
  'organza': 'or-GAN-zuh',
  'orgy': 'OR-jee',
  'orient': 'OR-ee-unt',
  'oriental': 'or-ee-EN-tul',
  'orientation': 'or-ee-un-TAY-shun',
  'oriented': 'OR-ee-un-tid',
  'orienting': 'OR-ee-un-ting',
  'orients': 'OR-ee-unts',
  'oriel': 'OR-ee-ul',
  'origin': 'OR-uh-jin',
  'original': 'uh-RIJ-uh-nul',
  'originality': 'uh-rij-uh-NAL-uh-tee',
  'originally': 'uh-RIJ-uh-nuh-lee',
  'originals': 'uh-RIJ-uh-nulz',
  'originate': 'uh-RIJ-uh-nayt',
  'originated': 'uh-RIJ-uh-nay-tid',
  'originates': 'uh-RIJ-uh-nayts',
  'originating': 'uh-RIJ-uh-nay-ting',
  'origins': 'OR-uh-jinz',
  'orinoco': 'or-uh-NOH-koh',
  'oriole': 'OR-ee-ohl',
  'ornament': 'OR-nuh-munt',
  'ornamental': 'or-nuh-MEN-tul',
  'ornaments': 'OR-nuh-munts',
  'ornate': 'or-NAYT',
  'ornithology': 'or-nuh-THOL-uh-jee',
  'orphan': 'OR-fun',
  'orphaned': 'OR-fund',
  'orphans': 'OR-funz',
  'orthodox': 'OR-thuh-doks',
  'orthodoxy': 'OR-thuh-dok-see',
  'osculatory': 'OS-kyuh-luh-tor-ee',
  'osloite': 'OS-loh-yt',
  'osteson': 'OS-tuh-sun',
  'ostrich': 'OS-trich',
  'other': 'UTH-er',
  'others': 'UTH-erz',
  'otherwise': 'UTH-er-wyz',
  'ought': 'AWT',
  'ounce': 'OWNS',
  'ounces': 'OWN-siz',
  'our': 'OWR',
  'ours': 'OWRZ',
  'ourselves': 'owr-SELVZ',
  'oust': 'OWST',
  'ousted': 'OW-stid',
  'ousting': 'OW-sting',
  'ousts': 'OWSTS',
  'out': 'OWT',
  'outage': 'OW-tij',
  'outages': 'OW-tij-iz',
  'outboard': 'OWT-bord',
  'outbreak': 'OWT-brayk',
  'outbreaks': 'OWT-brayks',
  'outburst': 'OWT-berst',
  'outbursts': 'OWT-bersts',
  'outcast': 'OWT-kast',
  'outcasts': 'OWT-kasts',
  'outcome': 'OWT-kum',
  'outcomes': 'OWT-kumz',
  'outcry': 'OWT-kry',
  'outdated': 'owt-DAY-tid',
  'outdid': 'owt-DID',
  'outdo': 'owt-DOO',
  'outdoes': 'owt-DOOZ',
  'outdoing': 'owt-DOO-ing',
  'outdone': 'owt-DUN',
  'outdoor': 'OWT-dor',
  'outdoors': 'owt-DORZ',
  'outer': 'OW-ter',
  'outermost': 'OW-ter-mohst',
  'outfit': 'OWT-fit',
  'outfits': 'OWT-fits',
  'outgoing': 'OWT-goh-ing',
  'outgrown': 'owt-GROHN',
  'outing': 'OW-ting',
  'outings': 'OW-tingz',
  'outlandish': 'owt-LAN-dish',
  'outlast': 'owt-LAST',
  'outlasted': 'owt-LAS-tid',
  'outlasting': 'owt-LAS-ting',
  'outlasts': 'owt-LASTS',
  'outlaw': 'OWT-law',
  'outlawed': 'OWT-lawd',
  'outlawing': 'OWT-law-ing',
  'outlaws': 'OWT-lawz',
  'outlet': 'OWT-let',
  'outlets': 'OWT-lets',
  'outline': 'OWT-lyn',
  'outlined': 'OWT-lynd',
  'outlines': 'OWT-lynz',
  'outlining': 'OWT-ly-ning',
  'outlook': 'OWT-look',
  'outlooks': 'OWT-looks',
  'outlying': 'OWT-ly-ing',
  'outnumber': 'owt-NUM-ber',
  'outnumbered': 'owt-NUM-berd',
  'outnumbering': 'owt-NUM-ber-ing',
  'outnumbers': 'owt-NUM-berz',
  'outpatient': 'OWT-pay-shunt',
  'outpatients': 'OWT-pay-shunts',
  'outpost': 'OWT-pohst',
  'outposts': 'OWT-pohsts',
  'output': 'OWT-poot',
  'outputs': 'OWT-poots',
  'outrage': 'OWT-rayj',
  'outraged': 'OWT-rayjd',
  'outrages': 'OWT-ray-jiz',
  'outrageous': 'owt-RAY-jus',
  'outraging': 'OWT-ray-jing',
  'outreach': 'OWT-reech',
  'outright': 'OWT-ryt',
  'outrun': 'owt-RUN',
  'outrunning': 'owt-RUN-ing',
  'outruns': 'owt-RUNZ',
  'outs': 'OWTS',
  'outset': 'OWT-set',
  'outside': 'owt-SYD',
  'outsider': 'owt-SY-der',
  'outsiders': 'owt-SY-derz',
  'outsides': 'owt-SYDZ',
  'outskirts': 'OWT-skerts',
  'outstanding': 'owt-STAN-ding',
  'outward': 'OWT-werd',
  'outwardly': 'OWT-werd-lee',
  'outweigh': 'owt-WAY',
  'outweighed': 'owt-WAYD',
  'outweighing': 'owt-WAY-ing',
  'outweighs': 'owt-WAYZ',
  'oval': 'OH-vul',
  'ovals': 'OH-vulz',
  'ovary': 'OH-vuh-ree',
  'ovation': 'oh-VAY-shun',
  'ovations': 'oh-VAY-shunz',
  'oven': 'UV-un',
  'ovens': 'UV-unz',
  'over': 'OH-ver',
  'overall': 'oh-ver-AWL',
  'overalls': 'OH-ver-awlz',
  'overboard': 'OH-ver-bord',
  'overcome': 'oh-ver-KUM',
  'overcomes': 'oh-ver-KUMZ',
  'overcoming': 'oh-ver-KUM-ing',
  'overdone': 'oh-ver-DUN',
  'overdose': 'OH-ver-dohs',
  'overdosed': 'OH-ver-dohst',
  'overdoses': 'OH-ver-dohs-iz',
  'overdosing': 'OH-ver-dohs-ing',
  'overdue': 'oh-ver-DOO',
  'overflow': 'OH-ver-floh',
  'overflowed': 'oh-ver-FLOHD',
  'overflowing': 'oh-ver-FLOH-ing',
  'overflows': 'OH-ver-flohz',
  'overgrown': 'oh-ver-GROHN',
  'overhaul': 'OH-ver-hawl',
  'overhauled': 'OH-ver-hawld',
  'overhauling': 'OH-ver-haw-ling',
  'overhauls': 'OH-ver-hawlz',
  'overhead': 'OH-ver-hed',
  'overhear': 'oh-ver-HEER',
  'overheard': 'oh-ver-HERD',
  'overhearing': 'oh-ver-HEER-ing',
  'overhears': 'oh-ver-HEERZ',
  'overlap': 'oh-ver-LAP',
  'overlapped': 'oh-ver-LAPT',
  'overlapping': 'oh-ver-LAP-ing',
  'overlaps': 'oh-ver-LAPS',
  'overlay': 'oh-ver-LAY',
  'overlaying': 'oh-ver-LAY-ing',
  'overlays': 'oh-ver-LAYZ',
  'overload': 'oh-ver-LOHD',
  'overloaded': 'oh-ver-LOH-did',
  'overloading': 'oh-ver-LOH-ding',
  'overloads': 'oh-ver-LOHDZ',
  'overlook': 'oh-ver-LOOK',
  'overlooked': 'oh-ver-LOOKT',
  'overlooking': 'oh-ver-LOOK-ing',
  'overlooks': 'oh-ver-LOOKS',
  'overnight': 'oh-ver-NYT',
  'overpower': 'oh-ver-POW-er',
  'overpowered': 'oh-ver-POW-erd',
  'overpowering': 'oh-ver-POW-er-ing',
  'overpowers': 'oh-ver-POW-erz',
  'override': 'oh-ver-RYD',
  'overrides': 'oh-ver-RYDZ',
  'overriding': 'oh-ver-RY-ding',
  'overrode': 'oh-ver-ROHD',
  'overrun': 'oh-ver-RUN',
  'overrunning': 'oh-ver-RUN-ing',
  'overruns': 'oh-ver-RUNZ',
  'overseas': 'oh-ver-SEEZ',
  'oversee': 'oh-ver-SEE',
  'overseeing': 'oh-ver-SEE-ing',
  'overseen': 'oh-ver-SEEN',
  'overseer': 'OH-ver-see-er',
  'overseers': 'OH-ver-see-erz',
  'oversees': 'oh-ver-SEEZ',
  'oversight': 'OH-ver-syt',
  'oversights': 'OH-ver-syts',
  'overstate': 'oh-ver-STAYT',
  'overstated': 'oh-ver-STAY-tid',
  'overstates': 'oh-ver-STAYTS',
  'overstating': 'oh-ver-STAY-ting',
  'overt': 'oh-VERT',
  'overtake': 'oh-ver-TAYK',
  'overtaken': 'oh-ver-TAY-kun',
  'overtakes': 'oh-ver-TAYKS',
  'overtaking': 'oh-ver-TAY-king',
  'overthrow': 'oh-ver-THROH',
  'overthrown': 'oh-ver-THROHN',
  'overthrows': 'oh-ver-THROHZ',
  'overtime': 'OH-ver-tym',
  'overtly': 'oh-VERT-lee',
  'overtook': 'oh-ver-TOOK',
  'overture': 'OH-ver-cher',
  'overtures': 'OH-ver-cherz',
  'overturn': 'oh-ver-TERN',
  'overturned': 'oh-ver-TERND',
  'overturning': 'oh-ver-TER-ning',
  'overturns': 'oh-ver-TERNZ',
  'overview': 'OH-ver-vyoo',
  'overviews': 'OH-ver-vyooz',
  'overwhelm': 'oh-ver-HWELM',
  'overwhelmed': 'oh-ver-HWEMD',
  'overwhelming': 'oh-ver-HWEL-ming',
  'overwhelmingly': 'oh-ver-HWEL-ming-lee',
  'overwhelms': 'oh-ver-HWELMZ',
  'owe': 'OH',
  'owed': 'OHD',
  'owes': 'OHZ',
  'owing': 'OH-ing',
  'owl': 'OWL',
  'owls': 'OWLZ',
  'own': 'OHN',
  'owned': 'OHND',
  'owner': 'OH-ner',
  'owners': 'OH-nerz',
  'ownership': 'OH-ner-ship',
  'owning': 'OH-ning',
  'owns': 'OHNZ',
  'ox': 'OKS',
  'oxen': 'OK-sun',
  'oxford': 'OKS-ferd',
  'oxide': 'OK-syd',
  'oxides': 'OK-sydz',
  'oxygen': 'OK-suh-jun',
  'oyster': 'OY-ster',
  'oysters': 'OY-sterz',
  'ozone': 'OH-zohn'
};

async function updateOWords() {
  try {
    console.log('Processing O-words pronunciation batch...');
    
    // Get O-words missing pronunciations
    const { data: wordsToUpdate, error } = await supabase
      .from('spelling_words')
      .select('id, word')
      .is('pronunciation_guide', null)
      .ilike('word', 'o%')
      .limit(250);
      
    if (error) {
      console.error('Error fetching words:', error);
      return;
    }
    
    console.log(`Found ${wordsToUpdate.length} O-words missing pronunciation`);
    let updated = 0;
    let notFound = [];
    
    for (const wordData of wordsToUpdate) {
      const word = wordData.word;
      const pronunciation = pronunciations[word] || pronunciations[word.toLowerCase()];
      
      if (pronunciation) {
        const { error: updateError } = await supabase
          .from('spelling_words')
          .update({ pronunciation_guide: pronunciation })
          .eq('id', wordData.id);
          
        if (updateError) {
          console.error(`Failed to update ${word}:`, updateError);
        } else {
          console.log(`✓ Added pronunciation for ${word}: ${pronunciation}`);
          updated++;
        }
        
        // Small delay to avoid rate limits
        await new Promise(resolve => setTimeout(resolve, 50));
      } else {
        notFound.push(word);
      }
    }
    
    console.log(`\nO-words batch completed: ${updated} pronunciations added`);
    
    if (notFound.length > 0) {
      console.log(`O-words not found in our list: ${notFound.length}`);
      if (notFound.length <= 30) {
        console.log('Missing O-words:');
        notFound.forEach(word => console.log(`- ${word}`));
      }
    }
    
    // Overall progress check
    const { count: totalCount } = await supabase
      .from('spelling_words')
      .select('*', { count: 'exact', head: true });
      
    const { count: withPronunciation } = await supabase
      .from('spelling_words')
      .select('*', { count: 'exact', head: true })
      .not('pronunciation_guide', 'is', null);
      
    const progress = ((withPronunciation/totalCount)*100).toFixed(1);
    console.log(`\nOverall progress: ${withPronunciation}/${totalCount} (${progress}%)`);
    
  } catch (error) {
    console.error('O-words batch failed:', error);
  }
}

updateOWords();